### ISSUE TITLE
Picture display functionality 

### ISSUE THREAD

**Issue by Sam-Walters93** [Sam-Walters93/hike-finder#17]
Picture display buttons currently do not function. 

Function currently relies on a direct click of button div. Due to the necessary structure of the button, this occurs only about 20% of the time. 

We could: 
1. add next/previous id's to all button elements
2. search up the HTML tree on click to find necessary id 
3. link JS functions to HTML structure ie "<button onclick="doFunction();" />"

**Comment by hbbc248** [comment]
completed
